name: Generate Pacman Animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Pacman
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: jayukarde10

      - name: Move pacman.svg to root
        run: |
          ls dist
          mv dist/pacman.svg pacman.svg

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add pacman.svg
          git commit -m "Update pacman animation" || echo "No changes"
          git push
